In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
print (np.__version__)

2.0.2


CREATING ARRAYS


In [ ]:
list1=(1,2,3)
print(list1)

(1, 2, 3)


In [ ]:
arr_list1=np.array(list1)## np.array convert the list to array
print(arr_list1)

[1 2 3]


In [ ]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [ ]:
list1=[1,2,3]
list2=[4,5,6]
arr1=np.array([list1,list2])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,22,9]
arr2=np.array([list1,list2,list3])
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7 22  9]]


In [ ]:
print(arr1.ndim)

2


In [ ]:
print(arr2.ndim)

2


#numpy array attributes


In [ ]:
print("shape",arr1.shape)
print("size",arr1.size)
print("dtype",arr1.dtype)
print("n_dim",arr1.ndim)


shape (2, 3)
size 6
dtype int64
n_dim 2


In [ ]:
print("shape",arr2.shape)
print("size",arr2.size)
print("dtype",arr2.dtype)
print("n_dim",arr2.ndim)


shape (3, 3)
size 9
dtype int64
n_dim 2


#Array initialization methods

In [ ]:
#zero array methods

zero_arr=np.zeros((2,3))

In [ ]:
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#one array methods

one_arr=np.ones((3,3))

In [ ]:
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#full array
fuu_arr=np.full((3,2),9)

In [ ]:
print(fuu_arr)

[[9 9]
 [9 9]
 [9 9]]


In [ ]:
#identity metrix always 3*3
id_arr =np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#empty array generate random value
print(np.empty(2))

[-1.18396664e+22  3.00941545e-69]


In [ ]:
#evenlyb space array
print(np.arange(2,10,2))


[2 4 6 8]


In [ ]:
print (np.arange(2,10,2))


[2 4 6 8]


In [ ]:
#specifioc values eqaly space  betweeen a range
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [ ]:
#random values array
r_arr=np.random.rand(3,3)
print(r_arr)

[[0.08401503 0.22922006 0.81624591]
 [0.61834928 0.11362742 0.51417056]
 [0.57099867 0.50736679 0.82251926]]


In [ ]:
#random values array
#random values array
# between 1 to 100 value and 63*3 matrix

rint_arr=np.random.randint(1,100,(3,3))
print(rint_arr)

[[87 32 42]
 [10 98 98]
 [82 15 56]]


In [ ]:
#array indexing
a=np.array([1,2,4,7,5])

In [ ]:
print(a)

[1 2 4 7 5]


In [ ]:
print(a[0])

1


In [ ]:
#slicing :
#$array[start:stop:step]# stop is include in output
print (a[0:3])

[1 2 4]


In [ ]:
 print (a[-1])#last elecment

5


In [ ]:
 print (a[-3:])#last 3 element

[4 7 5]


In [ ]:
print (a[1:4])#middle element(start :stop)

[2 4 7]


In [ ]:
arr4=np.array([[1,2,3],[4,5,6]])
print (arr4)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr4[0])

[1 2 3]


In [ ]:
print(arr4[0][0])

1


In [ ]:
print (arr4[1])#giving the array  it is one dimentional
print(arr4[1:])#give the dimention it is 2 dimentional #slising

[4 5 6]
[[4 5 6]]


In [ ]:
print(arr4[:1])#     arr [:stop]

[[1 2 3]]


In [ ]:
print(arr4[:2])    # arr[:stop]

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr4[:, 2]) #arr[row_number :,  column_number]

[3 6]


In [ ]:
print(arr4[:,0])

[1 4]


In [ ]:
arr5 = np.array([[1,2,3],
                [4,5,6],
                [7,5,3]])

In [ ]:
print(arr5)

[[1 2 3]
 [4 5 6]
 [7 5 3]]


In [ ]:
print (arr5[0])
print (arr5[1])
print (arr5[2])

[1 2 3]
[4 5 6]
[7 5 3]


In [ ]:
print (arr5[:,0])#1 st column value
print (arr5[:,1])#2 st column vvalue
print (arr5[:,2])#3 st column value



[1 4 7]
[2 5 5]
[3 6 3]


In [ ]:
print(arr5)

[[1 2 3]
 [4 5 6]
 [7 5 3]]


In [ ]:
print (arr5[::, 2])# arr[::,coloumn]

[3 6 3]


In [ ]:
print (arr5[2:3:, 1])    # arr(stare_row:stop_row:jump    :  ,  start_cloumn:end_column )             # ending column not ncluded

[5]


In [ ]:
#array reshaping
arr5=np.array([4,5,8,9,6,3])
print(arr5)

[4 5 8 9 6 3]


In [ ]:
reshaped=arr5.reshape((6,1))   #[6row,1column]
print(reshaped)

[[4]
 [5]
 [8]
 [9]
 [6]
 [3]]


In [ ]:
reshaped1=arr5.reshape((3,2))   #[6row,1column]
print(reshaped1)

[[4 5]
 [8 9]
 [6 3]]


In [ ]:
reshaped3=arr5.reshape((2,3))   #[6row,1column]   becoming 2d array
print(reshaped3)

[[4 5 8]
 [9 6 3]]


In [ ]:
print (reshaped3.flatten())   #become on 1 d array

[4 5 8 9 6 3]


Array Stacking And splitting



In [ ]:
a= np.array([1,2,3])
b= np.array([4,5,6])
print(np.vstack((a,b)))# vertical staking  making 1 D Array TO 2 D Array

[[1 2 3]
 [4 5 6]]


In [ ]:
a= np.array([1,2,3])
b= np.array([4,5,6])
print(np.hstack((a,b)))#horinzental stacking  making no changes to dimentional(D)

[1 2 3 4 5 6]


In [ ]:
c=np.array([[1,2,3],[4,5,6]])
print(c)


[[1 2 3]
 [4 5 6]]


splitting

In [ ]:
print(np.hsplit(c,3)) # general

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [ ]:
split = np.hsplit(c,3)

for s in split:
  print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [ ]:
split = np.hsplit(c,3)
print(split[0])


[[1]
 [4]]


In [ ]:
split = np.hsplit(c,3)
print(split[1])

[[2]
 [5]]


In [ ]:
vsplit = np.vsplit(c,2)

for s in vsplit:
  print(s)

[[1 2 3]]
[[4 5 6]]


In [ ]:
#Mathematical operation


In [ ]:
a= np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]


In [ ]:
print(a+2)
print(a-30)
print(a*5)
print(a/10)

[ 12  22  42 -28]
[-20 -10  10 -60]
[  50  100  200 -150]
[ 1.  2.  4. -3.]


In [ ]:
b=np.array([1,9,16])
print(b)

[ 1  9 16]


In [ ]:
print(np.square(b))
print(np.sqrt(b))

[  1  81 256]
[1. 3. 4.]


#sin cos tan

In [ ]:
#mat5hematical operation  on multiploy barray


In [ ]:
p=np.array([[1,2,3],[4,5,6]])
print(p)
print(p.T) # here T is transpose  it convert the ROW to COLUMN SO 2*3 MATRICS BECOM 3*2

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


STATISTICAL ARRAY

In [ ]:
print(np.min(p)) #min num
print(np.max(p))#max NUM
print(np.mean(p))3# MEAN
print(np.median(p))#MEDIAN
print(np.std(p))#Standerd deviation
print(np.var(p))#

1
6
3.5
3.5
1.707825127659933
2.9166666666666665


In [ ]:
a= np.array([1,5,3])
b= np.array([4,5,6])

In [ ]:
print (a == b )  #element wise

[False  True False]


In [ ]:
a= np.array([1,5,3])
b= np.array([4,5,6])
print(np.array_equal(a,b))# compering compleate array


False


BROADCASTION

In [ ]:
a= np.array([1,5,3]) #as lower dimentional array can perfrom operation on higher dimentiponal array
b= np.array([4])
print(a+b)

[5 9 7]


In [ ]:
a= np.array([[1,5,3],[2,5,8]]) #as lower dimentional(d) array can perfrom operation on higher dimentional(d) array
b= np.array([41,25,24])
print(a+b)

[[42 30 27]
 [43 30 32]]


Handling with nan

In [ ]:
akashnil =np.array([1,2,np.nan,4,np.inf])
print(akashnil)

[ 1.  2. nan  4. inf]


In [ ]:
print(np.isnan(akashnil))

[False False  True False False]


In [ ]:
#replace the nan value to 0

print (np.nan_to_num(akashnil))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]
